### ISSUE TITLE
Flexibel adding to the existing fields

### ISSUE THREAD

**Issue by jankout** [Craffft/contao-calendar-ical-bundle#11]
Hello, 

it would be nice to have more flexibel possibility to add calendar to all existing fields in the databank. I added the missing field manually. I think it would be more easier when your extension would check which fields are in the database already and shows them all. 

What do you think? 

Best wishes

**Comment by iCodr8** [comment]
Yes, this would much better. Can you add it as a pull request please?

**Comment by jankout** [comment]
I would like to do it but, unfortunately, I don't know how the code should be. Do you have any idea?

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
