### ISSUE TITLE
Curl Support für contao-calendar-ical-bundle

### ISSUE THREAD

**Issue by Acta2000** [Craffft/contao-calendar-ical-bundle#12]
Wenn man die Erweiterung hinter einem Proxy betreibt muss man dem CURL Proxy, Benutzernamen und Passwort mitgeben.  

Ich habe die Erweiterung etwas angepasst und den Curl-Proxy als drei Felder in den Kalendereinstellungen hinterlegt.

Die Änderungen betreffen vor allem contao/classes/CalendarImport.php
Dort Zeile 92, 99, 108, 121

Die anderen Änderungen betreffen nur die DCA und die deutschen Sprachfiles

[craffft_update_version_4.zip](https://github.com/Craffft/contao-calendar-ical-bundle/files/3380623/craffft_update_version_4.zip)

EDIT: Nun mit richtiger Ordner und Datei-Struktur
EDIT 2: Nun mit kleiner If-Abfrage damit die Nutzung auch ohne Proxy funktioniert!

**Comment by iCodr8** [comment]
Kannst du das bitte in einen pull request verpacken?

**Comment by Acta2000** [comment]
Hab ich mach gemacht. hoffe das war so richtig .. war mein erster Pull ever!

**Comment by iCodr8** [comment]
Sehr gut :)

**Comment by iCodr8** [comment]
Done in https://github.com/Craffft/contao-calendar-ical-bundle/pull/13
