### ISSUE TITLE
change path of ics file

### ISSUE THREAD

**Issue by Flaschenzug** [Craffft/contao-calendar-ical-bundle#16]
It would be a nice feature, to add a path for the ICS file in contao.
Is it possible to implement that in on of the next versions?

$path = "files/ical-hidden/";

protected function generateFiles($arrArchive)
	{
		...
		$objFile = new File($path.$filename . ".ics");
		...
	}

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
