### ISSUE TITLE
import ics data via URL

### ISSUE THREAD

**Issue by fred0815** [Craffft/contao-calendar-ical-bundle#21]
Hello,

we are importing ics data via URL in our current contao version.

part of ics data:

BEGIN:VEVENT
DESCRIPTION:auf Grund der neuen Bestimmungen ist das Training bis auf Weiteres eingestellt.
DTSTART;VALUE=DATE:20201111
SUMMARY:es findet kein Training statt
UID:3429b939cec922b6fa66
URL:https://xxxx
END:VEVENT

and get this event in contao:

![image](https://user-images.githubusercontent.com/6215447/97694921-8b0fec00-1aa3-11eb-9213-483016130782.png)

due to the enddate of "1999-11-29" the standard module "eventlist" in contao, the event will not be shown on the webside.

May be you can help us. Thanks a lot.

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
