### ISSUE TITLE
Import ics with DURATION

### ISSUE THREAD

**Issue by jammon88** [Craffft/contao-calendar-ical-bundle#22]
Hi there

I am a Contao user and use your plugin to import ICS files directly into Contao. But if the ICS file uses the DURATION field and has no DTEND field, the event is imported without an end time. Could you extend the plugin with this functionality?

Thanks and best regards

Jammon

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
