### ISSUE TITLE
Import LOCATION as Event location instead of a text element

### ISSUE THREAD

**Issue by jammon88** [Craffft/contao-calendar-ical-bundle#23]
Hi there

When importing an ICS file the LOCATION field is currently displayed as a separate text field. Could you customize the plugin to insert it into the Contao Event Location field? That would be great.

Thanks and best regards

Jammon

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
