### ISSUE TITLE
Conflict with PHP 8

### ISSUE THREAD

**Issue by dive13** [Craffft/contao-calendar-ical-bundle#24]
Contao 4.9.11

The extension seems not to be ready for PHP 8, while there is everything fine with PHP 7. The following conflict occurs after switching to PHP 8:

`Uncaught PHP Exception TypeError: "join(): Argument #2 ($array) must be of type ?array, string given" at /patht-o-project/vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarImport.php line 40 {"exception":"[object] (TypeError(code: 0): join(): Argument #2 ($array) must be of type ?array, string given at /path-to-project/vendor/craffft/contao-calendar-ical-bundle/src/Resources/contao/classes/CalendarImport.php:40)"} []`

Thanks

**Comment by gitpurzel** [comment]
same as https://github.com/hschottm/calendar_ical/issues/17
seems easy to fix

**Comment by rabauss** [comment]
Upgrade to the fork https://github.com/cgoIT/contao-calendar-ical-bundle

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
