### ISSUE TITLE
Contao 4.11.x and Symfony 5.x

### ISSUE THREAD

**Issue by jankout** [Craffft/contao-calendar-ical-bundle#25]
Hello, 

I have the same problem with your extension[ like with this extension](https://github.com/1up-lab/contao-mailchimp/issues/31).

**Comment by rabauss** [comment]
Maybe fixed with the fork https://github.com/cgoIT/contao-calendar-ical-bundle

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
