### ISSUE TITLE
Error when using with Contao 4.9.20 and Strict Mode and markocupic / calendar-event-booking-bundle

### ISSUE THREAD

**Issue by johannes-bittner** [Craffft/contao-calendar-ical-bundle#26]
When using Contao 4.9.20 and MySQL strict mode and [Craffft / contao-calendar-ical-bundle] (or maybe other extensions that write to tl_calendar_events), events cannot be created/get deleted (error message below).

**Here is what I do / what happens:**
- I install Crafft/iCal Calendar and enter the ics-calendar url for the Google Calendar
- The events from the Google Calendar are the automatically created as single events
- Then I install the calendar event booking bundle and open the calendar settings page in order to set the page for the unsubscription module; when I save the settings, I get the error message and the events from Google are gone
- I can create events in the backend and save them without any error or problem, but the events from the Google Calendar won't show up anymore
- Once I created an event in the calendar (manually), the error message won't appear, but I get them in the logs when iCal tries to sync with the Google Calendar

**Here is what Marco says:** 
> OK. It looks like the exeption is throwed in the Ical extension. CalendarImport::importFromICS() traverses the DCA field key and checks if a default value is set. If this is not the case the extension takes an empty string as default value. But this is not a good idea if the field requires an integer.
> It would be better not to set those empty fields at all and let the database set the correct empty value upon new inserts.
> As a workaround I added the 'default' key key to all these fields in the DCA.

**Error message:** 
`An exception occurred while executing 'INSERT INTO tl_calendar_events (`pid`, `tstamp`, `title`, `alias`, `author`, `addTime`, `startTime`, `endTime`, `startDate`, `endDate`, `pageTitle`, `description`, `location`, `address`, `teaser`, `addImage`, `overwriteMeta`, `singleSRC`, `alt`, `imageTitle`, `size`, `imagemargin`, `imageUrl`, `fullsize`, `caption`, `floating`, `recurring`, `repeatEach`, `repeatEnd`, `recurrences`, `addEnclosure`, `enclosure`, `orderEnclosure`, `source`, `jumpTo`, `articleId`, `url`, `target`, `cssClass`, `noComments`, `published`, `start`, `stop`, `unsubscribeLimitTstamp`, `unsubscribeLimit`, `enableDeregistration`, `eventBookingNotificationSender`, `eventBookingNotificationCenterIds`, `enableNotificationCenter`, `includeEscortsWhenCalculatingRegCount`, `maxEscortsPerMember`, `maxMembers`, `minMembers`, `bookingEndDate`, `bookingStartDate`, `enableMultiBookingWithSameAddress`, `addBookingForm`, `city`, `postal`, `street`) VALUES ('1', 1630395250, 'BELEGT', '', '1', '', 1631224800, 1631397600, 1631224800, 1631397600, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'above', '', '', '0', '0', '', '', '', 'default', '0', '0', '', '', '', '', 1, '', '', '', '0', '', '0', '', '', 0, 0, 0, 0, '', '', '', '', '', '', '')':

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'unsubscribeLimitTstamp' at row 1`

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
