### ISSUE TITLE
Export unvollständig

### ISSUE THREAD

**Issue by Ernestopheles** [Craffft/contao-calendar-ical-bundle#28]
Über contao-calendar-ical-php8-bundle erstelle ich .ics zum Abonnieren der events der Webseite.
Im Webseiten Kalender erscheinen alle events, im externen Kalender (und in der .ics) stehen nicht alle events: Bei Wiederholungen steht nur das nächste drin. Vermutlich deshalb, weil im eventlister "Nur nächste Wiederholung" angekreuzt ist. Das sollte sich aber imho nicht auf den Kalender (tut es ja auch nicht), und also auch nicht auf die .ics (tut es leider doch), sondern nur auf das Listmodul auswirken. Oder sehe ich das falsch?

**Comment by iCodr8** [comment]
The extension is NOT MAINTAINED.
Use this fork: https://github.com/cgoIT/contao-calendar-ical-bundle
