### ISSUE TITLE
Default values werden nicht korrekt festgelegt

### ISSUE THREAD

**Issue by pointout** [Craffft/contao-calendar-ical-bundle#32]
Ich bekomme eine Fehlermeldung, beim Import aus einer ics-Datei. Ich dachte erst es kommt vor Registrierungserweiterung.
Ich habe auch noch eigene Felder für Kalenderevents. Außerdem fehlt mir im DB Statement der Eventtitel aus der ical Datei.
Bitte schauen auf: https://github.com/inspiredminds/contao-event-registration/issues/16

Contao 4.9.40
cgoit/contao-calendar-ical-php8-bundle 4.4.9

**Comment by fritzmg** [comment]
@pointout I don't think this is the correct repository. According to the output you provided in https://github.com/inspiredminds/contao-event-registration/issues/16 you are using [`cgoit/contao-calendar-ical-php8-bundle`](https://github.com/cgoIT/contao-calendar-ical-bundle).

**Comment by pointout** [comment]
You are right! Thanks!

**Comment by pointout** [comment]
Posted in [cgoit/contao-calendar-ical-php8-bundle](https://github.com/cgoIT/contao-calendar-ical-bundle/issues/14)
